### ISSUE TITLE
Authentication Broken on QuizSubmissionForAnalysis Branch

### ISSUE THREAD

**Issue by alexv-anderson** [bcroden/QuizDeck-Server#50]
@CadeG something is wrong with the QuizSubmissionForAnalysis branch. I cleaned out all of the compile errors, and the authentication tests still fail. See build [#139](https://travis-ci.org/bcroden/QuizDeck-Server/branches). The tests seem to be failing mainly because of `NoSuchBeanDefinitionException`.

**Comment by alexv-anderson** [comment]
I found this on line 177 of the output of build [#139](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110258823)

```
177     :compileTestJavaNote: /home/travis/build/bcroden/QuizDeck-Server/src/test/java/com/quizdeck/controllers/AuthenticationControllerTest.java uses unchecked or unsafe operations.
```

Would this have anything to do with the error?

**Comment by bcroden** [comment]
No, that line is not the problem, some of the test signatures in that class state that they can throw exceptions, but those Exceptions are not explicitly expected by JUnit.

The problem is that CompletedQuizRepository and QuizRepository need to extend MongoRepository, otherwise Spring Doesn't know how to instantiate them when the tests ask for Spring to Autowire them.

Furthermore, the The repositories reference fields in CompleteQuiz that do not exist. Title and Owner to be precise. I have pushed a commit to the branch that should fix this.

**Comment by CadeG** [comment]
We were working on that branch in a meeting earlier and changed those
objects, forgot to update things.  My bad

**Comment by bcroden** [comment]
It's all good, the build is now passing. [#144](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110281773)
